### ISSUE TITLE
Macro editor should disallow nesting

### ISSUE THREAD

**Issue by MaximilianLloyd** [KinesisCorporation/Adv360-Pro-GUI#11]
Here, you have the possibility to add macros. But it breaks the build.

![image](https://github.com/KinesisCorporation/Adv360-Pro-GUI/assets/10583205/4df447c9-fb96-41bf-8de4-29a430b29413)

Run for reference: https://github.com/MaximilianLloyd/Adv360-Pro-ZMK/actions/runs/5084127947/jobs/9136019710

**Comment by KinesisCorporation** [comment]
Noted with thanks!

**Comment by KinesisCorporation** [comment]
This is now fixed.
