### ISSUE TITLE
Missing key toggle behavior

### ISSUE THREAD

**Issue by JafarAbdi** [KinesisCorporation/Adv360-Pro-GUI#2]
For some reason, I can't add a [toggle behavior](https://zmk.dev/docs/behaviors/key-toggle), it's not showing up when I press on the `select behavior` list

**Comment by KinesisCorporation** [comment]
Noted. We will work on adding this to the GUI.

**Comment by dylan-jh** [comment]
Just added &to and some other basic behaviors to the GUI. Try again please.

**Comment by KinesisCorporation** [comment]
Just added &to and some other basic behaviors to the GUI. Try again please.
