### ISSUE TITLE
&tog happy accepts zero input causing the build to fail

### ISSUE THREAD

**Issue by masters3d** [KinesisCorporation/Adv360-Pro-GUI#6]
![image](https://user-images.githubusercontent.com/6539412/210126215-b9da928a-7bac-4c96-a03f-ec112dbdf1e5.png)
The above should not be allowed to be checked in.

**Comment by KinesisCorporation** [comment]
thanks, on it!

**Comment by KinesisCorporation** [comment]
Fixed!
